### ISSUE TITLE
New ARM 

### ISSUE THREAD

**Issue by Htownmsp** [urighi/wvd-scripts#1]
Do you have plans to make this script work for the new ARM templates with the new ps modules they added?

Didn't realize this wouldn't work with the arm template and I'm stuck :(

**Comment by urighi** [comment]
It's still in public preview, so I would rather wait until it's released to update modules. So far I haven't worked with any host pools deployed with WVD as an ARM resource. You can probably modify the script to use the new Az.DesktopVirtualization module without any changes to the application logic.
